#pragma once

#define IOCTL_PROCESS_HIDE CTL_CODE(FILE_DEVICE_UNKNOWN, 0xdeadbeef, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

#define TEST_BRO 808

#define HIDE_STATUS_SUCCESS 808
#define HIDE_STATUS_FAILURE 404

#define ACTIVE_PROCESS_LINKS_FLINK 0x2f0
#define IMAGE_FILE_NAME 0x450
